### ISSUE TITLE
The logo is stretched vertically when the image is horizontally wide

### ISSUE THREAD

**Issue by yamavol** [cobapen/sphinx-theme-mochi#1]
height should not be 100% - this stretches the image.

```css
.sidebar-logo-container > img {
  height: 100%
}
```
